name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: initial checkout
      uses: actions/checkout@v2

    - name: cache Homebrew cache
      uses: actions/cache@v2
      with:
        path: /Users/runner/Library/Caches/Homebrew
        key: ${{ runner.os }}-sbt-${{ hashFiles('*.rb') }}

    - name: brew update
      run: brew update
    - name: tap riscv
      run: brew tap victoryang00/riscv
    - name: install tools
      run: arch -arm64 brew install riscv-tools
    - name: test
      run: arch -arm64 brew test riscv-tools
